export const instructors = [
    { name: 'All' },
    { name: 'Ana de Armas', specialty1: 'Pilates', specialty2: 'Yoga' },
    { name: 'Arnold Schwarzenegger', specialty1: 'Strength Training', specialty2: 'Cardio' },
    { name: 'Aubrey Graham', specialty1: 'Cardio', specialty2: 'HIIT' },
    { name: 'Dwayne Johnson', specialty1: 'Strength Training', specialty2: 'HIIT' },
    { name: 'Emma Watson', specialty1: 'Yoga', specialty2: 'Pilates' },
    { name: 'Eric Winter', specialty1: 'HIIT', specialty2: 'Strength Training' },
    { name: 'Hugh Jackman', specialty1: 'Strength Training', specialty2: 'Cardio' },
    { name: 'Jennifer Lawrence', specialty1: 'Cardio', specialty2: 'HIIT' },
    { name: 'Jennifer Lopez', specialty1: 'Cardio', specialty2: 'Yoga' },
    { name: 'Megan Fox', specialty1: 'Cardio', specialty2: 'Strength Training' },
    { name: 'Scarlett Johansson', specialty1: 'Pilates', specialty2: 'Yoga' },
    { name: 'Sofia Vergara', specialty1: 'Yoga', specialty2: 'Pilates' },
    { name: 'Timothee Chalamet', specialty1: 'Yoga', specialty2: 'Pilates' },
    { name: 'Tom Holland', specialty1: 'Cardio', specialty2: 'Strength Training' },
    { name: 'Will Smith', specialty1: 'HIIT', specialty2: 'Strength Training' },
    { name: 'Zara Larsson', specialty1: 'Yoga', specialty2: 'Cardio' }
  ];
  
  export const classNames = [
    { name: 'Cardio Blast', instructor: instructors[2], classType: 'Cardio', difficulty: 'Intermediate', duration: '< 30 minutes', equipment: 'No Equipment', format: 'Live', rating: '4 stars', date: '2024-08-15', time: '09:00 AM', description: 'An energetic cardio class to get your heart pumping!', price: '$16.95' },
    { name: 'Pilates Core', instructor: instructors[1], classType: 'Pilates', difficulty: 'Beginner', duration: '30 - 60 minutes', equipment: 'Yoga Mat', format: 'Live', rating: '5 stars', date: '2024-08-20', time: '10:00 AM', description: 'Strengthen your core with this pilates class.', price: '$22.60' },
    { name: 'HIIT Burn', instructor: instructors[3], classType: 'HIIT', difficulty: 'Advanced', duration: '< 30 minutes', equipment: 'No Equipment', format: 'Live', rating: '4 stars', date: '2024-08-25', time: '11:00 AM', description: 'High-intensity interval training to burn calories fast.', price: '$20.34' },
    { name: 'Strength Mastery', instructor: instructors[4], classType: 'Strength Training', difficulty: 'Intermediate', duration: '30 - 60 minutes', equipment: 'Dumbbells', format: 'Live', rating: '5 stars', date: '2024-08-30', time: '12:00 PM', description: 'Build your strength with this comprehensive workout.', price: '$24.86' },
    { name: 'Yoga Flow', instructor: instructors[5], classType: 'Yoga', difficulty: 'Beginner', duration: '> 60 minutes', equipment: 'Yoga Mat', format: 'On Demand', rating: '4 stars', description: 'A relaxing yoga session to enhance flexibility.', price: '$11.30' },
    { name: 'HIIT Cardio', instructor: instructors[6], classType: 'HIIT', difficulty: 'Advanced', duration: '< 30 minutes', equipment: 'Resistance Bands', format: 'Live', rating: '4 stars', date: '2024-09-05', time: '01:00 PM', description: 'A high-energy HIIT workout for cardio improvement.', price: '$20.34' },
    { name: 'Cardio Dance', instructor: instructors[8], classType: 'Cardio', difficulty: 'Beginner', duration: '< 30 minutes', equipment: 'No Equipment', format: 'Live', rating: '3 stars', date: '2024-09-10', time: '02:00 PM', description: 'Dance your way to fitness with this cardio class.', price: '$13.56' },
    { name: 'Yoga for Beginners', instructor: instructors[9], classType: 'Yoga', difficulty: 'Beginner', duration: '30 - 60 minutes', equipment: 'Yoga Mat', format: 'On Demand', rating: '4 stars', description: 'Perfect for those new to yoga.', price: '$11.30' },
    { name: 'Pilates Sculpt', instructor: instructors[10], classType: 'Pilates', difficulty: 'Intermediate', duration: '30 - 60 minutes', equipment: 'No Equipment', format: 'Live', rating: '5 stars', date: '2024-09-15', time: '03:00 PM', description: 'Tone your body with pilates sculpting exercises.', price: '$22.60' },
    { name: 'Strength HIIT', instructor: instructors[11], classType: 'Strength Training', difficulty: 'Advanced', duration: '30 - 60 minutes', equipment: 'Resistance Bands', format: 'On Demand', rating: '4 stars', description: 'Combine strength training with HIIT for a full workout.', price: '$20.34' },
    { name: 'Yoga Relaxation', instructor: instructors[12], classType: 'Yoga', difficulty: 'Beginner', duration: '> 60 minutes', equipment: 'Yoga Mat', format: 'Live', rating: '4 stars', date: '2024-09-20', time: '04:00 PM', description: 'Relax and unwind with this gentle yoga class.', price: '$13.56' },
    { name: 'Cardio Power', instructor: instructors[13], classType: 'Cardio', difficulty: 'Advanced', duration: '< 30 minutes', equipment: 'No Equipment', format: 'On Demand', rating: '3 stars', description: 'Boost your cardio with power moves.', price: '$16.95' },
    { name: 'Pilates Flexibility', instructor: instructors[14], classType: 'Pilates', difficulty: 'Intermediate', duration: '30 - 60 minutes', equipment: 'Yoga Mat', format: 'Live', rating: '5 stars', date: '2024-09-25', time: '05:00 PM', description: 'Enhance your flexibility with pilates.', price: '$22.60' },
    { name: 'Strength Endurance', instructor: instructors[15], classType: 'Strength Training', difficulty: 'Advanced', duration: '> 60 minutes', equipment: 'Dumbbells', format: 'On Demand', rating: '4 stars', description: 'Build endurance and strength in this class.', price: '$20.34' },
    { name: 'HIIT Energy', instructor: instructors[16], classType: 'HIIT', difficulty: 'Intermediate', duration: '< 30 minutes', equipment: 'No Equipment', format: 'Live', rating: '5 stars', date: '2024-09-30', time: '06:00 PM', description: 'Get energized with this high-intensity workout.', price: '$20.34' },
    { name: 'Cardio Kick', instructor: instructors[2], classType: 'Cardio', difficulty: 'Intermediate', duration: '30 - 60 minutes', equipment: 'No Equipment', format: 'On Demand', rating: '4 stars', description: 'Kick your way to fitness with cardio moves.', price: '$16.95' },
    { name: 'Pilates for Strength', instructor: instructors[1], classType: 'Pilates', difficulty: 'Beginner', duration: '30 - 60 minutes', equipment: 'Resistance Bands', format: 'Live', rating: '5 stars', date: '2024-10-05', time: '07:00 PM', description: 'Strengthen your body with pilates.', price: '$22.60' },
    { name: 'HIIT Challenge', instructor: instructors[3], classType: 'HIIT', difficulty: 'Advanced', duration: '30 - 60 minutes', equipment: 'No Equipment', format: 'Live', rating: '4 stars', date: '2024-10-10', time: '08:00 PM', description: 'Challenge yourself with this intense HIIT class.', price: '$20.34' },
    { name: 'Strength Building', instructor: instructors[4], classType: 'Strength Training', difficulty: 'Intermediate', duration: '> 60 minutes', equipment: 'Dumbbells', format: 'On Demand', rating: '5 stars', description: 'Build muscle with targeted strength exercises.', price: '$22.60' },
    { name: 'Yoga Serenity', instructor: instructors[5], classType: 'Yoga', difficulty: 'Beginner', duration: '> 60 minutes', equipment: 'Yoga Mat', format: 'Live', rating: '4 stars', date: '2024-10-15', time: '09:00 PM', description: 'Find serenity with this calming yoga session.', price: '$13.56' },
    { name: 'Cardio Strength', instructor: instructors[6], classType: 'Cardio', difficulty: 'Intermediate', duration: '< 30 minutes', equipment: 'No Equipment', format: 'On Demand', rating: '5 stars', description: 'Combine cardio and strength in one workout.', price: '$16.95' },
    { name: 'Pilates Precision', instructor: instructors[7], classType: 'Pilates', difficulty: 'Beginner', duration: '30 - 60 minutes', equipment: 'Yoga Mat', format: 'Live', rating: '4 stars', date: '2024-10-20', time: '09:00 AM', description: 'Focus on precision and control in pilates.', price: '$22.60' },
    { name: 'HIIT Blast', instructor: instructors[8], classType: 'HIIT', difficulty: 'Advanced', duration: '30 - 60 minutes', equipment: 'Resistance Bands', format: 'On Demand', rating: '4 stars', description: 'Blast calories with high-intensity intervals.', price: '$20.34' },
    { name: 'Strength for Beginners', instructor: instructors[9], classType: 'Strength Training', difficulty: 'Beginner', duration: '30 - 60 minutes', equipment: 'Dumbbells', format: 'Live', rating: '5 stars', date: '2024-10-25', time: '10:00 AM', description: 'Perfect for those new to strength training.', price: '$22.60' },
    { name: 'Yoga Energy', instructor: instructors[10], classType: 'Yoga', difficulty: 'Intermediate', duration: '> 60 minutes', equipment: 'Yoga Mat', format: 'On Demand', rating: '4 stars', description: 'Energize your body and mind with yoga.', price: '$13.56' },
    { name: 'Cardio Sculpt', instructor: instructors[11], classType: 'Cardio', difficulty: 'Advanced', duration: '< 30 minutes', equipment: 'No Equipment', format: 'Live', rating: '3 stars', date: '2024-10-30', time: '11:00 AM', description: 'Sculpt your body with cardio moves.', price: '$16.95' },
    { name: 'Pilates Balance', instructor: instructors[12], classType: 'Pilates', difficulty: 'Beginner', duration: '30 - 60 minutes', equipment: 'Yoga Mat', format: 'On Demand', rating: '5 stars', description: 'Improve balance and flexibility with pilates.', price: '$22.60' },
    { name: 'Strength Circuit', instructor: instructors[13], classType: 'Strength Training', difficulty: 'Intermediate', duration: '30 - 60 minutes', equipment: 'Dumbbells', format: 'Live', rating: '4 stars', date: '2024-11-05', time: '12:00 PM', description: 'Circuit training to build strength.', price: '$22.60' },
];

  